// Generated by CoffeeScript 1.4.0
(function() {
  var students;

  students = ["Megan Tulac", "Nathan Houle", "Timothy Schiller", "Adnan Wahab", "JP Whitaker", "Carey Winslow", "Mark Chatkhan", "Christen Thompson", "Sherah Smith", "Mark Rossetti", "Henry Zhu", "Albert Lee", "Paul Bacchus", "Mark Reveley", "Chris Bobek", "June Jeong"];

}).call(this);
